tag_checker:
  stage: build
  script:
    - python tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

junit:
  stage: test
  script:
    - sbt test

recent-artifacts:
  stage: deploy
  script:
    - sbt dist
  artifacts:
    paths:
      - target/universal/*.zip
    expire_in: 1 week
  except:
    - tags

release-artifacts:
 stage: deploy
 script:
    - sbt dist
 artifacts:
    paths:
    - target/universal/*.zip
 only:
    - tags


deploy-dev:
  stage: deploy

  script:
  - echo "Deploy to development server"
  - sbt dist
  - cd /var/lib/gitlab-runner/builds/cc082478/0/seng302-2019/team-700/target/universal
  - ls
  - unzip -d *.zip
  - cd seng302-team-700-0.0.1-SNAPSHOT/bin
  - chmod +x seng302-team-700
  - ./seng302-team-700 -Dplay.http.secret.key='zHEyLENJwfBB88RsrMBW' -Dhttp.port=8080

  only:
    #For now only deploy when committing from the test branch.
    #TODO change to master branch when working.
  - dedicatedServerTest@seng302-2019/team-700
  except:
  - tags

#deploy-prod:
#
# stage: deploy
#
# script:
#   - echo "Deploy to production server"
#   - sbt dist
#  - unzip -d target/universal/*.zip
#  - cd target/universal/seng302-team-700-0.0.1-SNAPSHOT/bin
#  - chmod +x seng302-team-700
#  - ./seng302-team-700 -Dplay.http.secret.key='zHEyLENJwfBB88RsrMBW' -Dhttp.port=80
#
# only:
#  - master@seng302-2019/team-700
#  - tags



update-sonar:
  stage: deploy
  script:
    - export PATH=$PATH:/opt/sonar-scanner/bin
    - sonar-scanner
  only:
    - SessionAuthUpgrade@seng302-2019/team-700