tag_checker:
  stage: build
  script:
    - python tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

junit:
  stage: test
  script:
    - sudo update-java-alternatives --set java-8-oracle
    - sbt jacoco
    - sudo mkdir /home/JACOCO && cp -r target/ /home/JACOCO/
    - sudo update-java-alternatives --set java-1.11.0-openjdk-amd64
  artifacts:
    paths:
      - target/scala-2.12/classes/
      - target/scala-2.12/jacoco/data/jacoco.exec
      - target/*


#coverage:
#  stage: deploy
#  script:
#    - sbt clean jacoco

recent-artifacts:
  stage: deploy
  script:
    - sbt dist
  artifacts:
    paths:
      - target/universal/*.zip
    expire_in: 1 week
  except:
    - tags

release-artifacts:
 stage: deploy
 script:
    - sbt dist
 artifacts:
    paths:
    - target/universal/*.zip
    - target/*
 only:
    - tags

update-sonar:
  stage: deploy
  script:
    - export PATH=$PATH:/opt/sonar-scanner/bin
    - sonar-scanner
  artifacts:
    paths:
    - target/*
  only:
    - sonar-qube@seng302-2019/team-700