tag_checker:
  stage: build
  script:
    - python tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

junit:
  stage: test
  script:
    - sbt jacoco
    - mkdir jacoco
    - cp -r target/scala-2.12/jacoco/report/test jacoco

#coverage:
#  stage: deploy
#  script:
#    - sbt clean jacoco

recent-artifacts:
  stage: deploy
  script:
    - sbt dist
  artifacts:
    paths:
      - target/universal/*.zip
    expire_in: 1 week
  except:
    - tags

release-artifacts:
 stage: deploy
 script:
    - sbt dist
 artifacts:
    paths:
    - target/universal/*.zip
 only:
    - tags

update-sonar:
  stage: deploy
  script:
    - export PATH=$PATH:/opt/sonar-scanner/bin
    - sonar-scanner
  only:
    - sonar-qube@seng302-2019/team-700